export const metadata = {
  title: "Terms of Service — WingAgent",
  description: "Read the terms governing your use of WingAgent and our AI automation platform.",
};

export default function TermsPage() {
  return (
    <main className="max-w-4xl mx-auto px-6 py-24 text-slate-300">
      <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>
      <p className="mb-4">
        These Terms of Service ("Terms") govern your access to and use of WingAgent,
        a service operated by Public Affairs Analytics LLC ("we," "us"). By using the
        platform you agree to these Terms.
      </p>
      <h2 className="text-xl text-white mt-8 mb-2">1. Eligibility</h2>
      <p>Users must be 18 years or older and have valid accounts on supported dating platforms.</p>
      <h2 className="text-xl text-white mt-8 mb-2">2. Acceptable Use</h2>
      <p>Automation must comply with local laws and platform guidelines. Users remain
         responsible for messages sent through their linked profiles.</p>
      <h2 className="text-xl text-white mt-8 mb-2">3. Privacy & Data</h2>
      <p>WingAgent stores only encrypted credentials. We never sell or share user data.</p>
      <h2 className="text-xl text-white mt-8 mb-2">4. Billing</h2>
      <p>Subscription fees renew automatically each month unless canceled through your dashboard.</p>
      <h2 className="text-xl text-white mt-8 mb-2">5. Liability</h2>
      <p>WingAgent is provided “as is.” We are not responsible for interactions resulting
         from messages generated by the system.</p>
      <h2 className="text-xl text-white mt-8 mb-2">6. Updates</h2>
      <p>We may modify these Terms at any time; continued use constitutes acceptance.</p>
    </main>
  );
}